name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Erlaubt manuelle Auslösung des Workflows
  workflow_dispatch:

# Berechtigungen für das GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Nur ein gleichzeitiges Deployment zulassen
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only the public directory (website files)
          path: './public'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Deployment Info
        run: |
          echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
          echo "Deployment time: $(date)"